// <auto-generated />
namespace FishBack.DataAccess.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class removed_FishEvent_relationship_from_BlogEntry : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removed_FishEvent_relationship_from_BlogEntry));
        
        string IMigrationMetadata.Id
        {
            get { return "201211201127143_removed_FishEvent_relationship_from_BlogEntry"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
