// <auto-generated />
namespace FishBack.DataAccess.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class FileNameSuffix_image : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FileNameSuffix_image));
        
        string IMigrationMetadata.Id
        {
            get { return "201211210826030_FileNameSuffix_image"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
