// <auto-generated />
namespace FishBack.DataAccess.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Tag_entity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Tag_entity));
        
        string IMigrationMetadata.Id
        {
            get { return "201211220824384_Tag_entity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
