// <auto-generated />
namespace FishBack.DataAccess.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Changes_in_Image : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changes_in_Image));
        
        string IMigrationMetadata.Id
        {
            get { return "201212061454185_Changes_in_Image"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
