// <auto-generated />
namespace FishBack.DataAccess.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class BlogEntry_Image_FishEvent_Location : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BlogEntry_Image_FishEvent_Location));
        
        string IMigrationMetadata.Id
        {
            get { return "201211141137192_BlogEntry_Image_FishEvent_Location"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
