// <auto-generated />
namespace FishBack.DataAccess.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class added_some_user_properties : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_some_user_properties));
        
        string IMigrationMetadata.Id
        {
            get { return "201211200844174_added_some_user_properties"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
